blank_issues_enabled: true
contact_links:
  - name: ğŸ“± WhatsApp Support
    url: https://wa.me/5537998553430
    about: Suporte e dÃºvidas rÃ¡pidas.
  - name: ğŸ“š Documentation
    url: https://github.com/ossmoralus/galeria/tree/main/docs
    about: Consulte nossa documentaÃ§Ã£o completa antes de abrir uma issue
  - name: ğŸŒ Website
    url: https://galeria-drab.vercel.app
    about: Visite nosso site para ver a galeria completa e gerador de badges
